app/models/match.rb
app/models/qualifier.rb
db/migrate/20171103210105_add_result_columns_on_matches.rb
db/schema.rb
spec/factories/matches.rb
spec/models/match_spec.rb

`Qualifier` 1 : n `QualifierMatch` 1 : n `Match` の関係から、 `Qualifier` 1 : n `Match` になるように変更

Qualifier 1 : n Match の関係になるようにカラム追加

---

app/controllers/matches_controller.rb

試合結果反映コントローラの修正

---

app/assets/stylesheets/events.scss
app/views/events/_ranking.html.erb
app/views/qualifiers/matches.html.erb

Makbook Air で720pの画面に投影したときにレイアウトが崩れた
各種表でセル幅を指定する

1280 x 720 に最適化する

---

app/models/match.rb
app/services/drawer.rb

[同一対戦カードを回避して組み合わせを作る #30](#30)

[#30] スイスドローの抽選処理を改善

---

app/javascript/src/events.scss

Win, Lose, Draw のバッチ幅を揃えたい #53

[#53] 🛠 勝敗表示のバッヂサイズを揃える

---

app/views/events/top.html.erb

[#55] 対戦部屋未設定の試合での表示を修正

---

app/services/room_allocator.rb

🛠 優先度高い部屋の割当方法を見直し

---

app/views/qualifiers/matches.html.erb

[#71] Sort by room

---

app/javascript/src/header.scss

[#76] A sidebar collapsed.

---

app/controllers/events_controller.rb
app/models/team.rb
app/views/events/_ranking.html.erb

- 勝ち点が並んだ場合の序列を決めるために Opponent Match Win Percentage を算出する #82

[#82] Implements opponent match win percentage

---

app/services/drawer.rb

- tier 考慮したマッチングは Round1 だけにする #84

[#84] tier 考慮マッチングはRound1だけ

---

app/services/room_allocator.rb

- 配信卓の最終戦は上位チーム同士の対戦に割り当てる制約を外す #86

[#86] 配信卓のアサインを見直し

---

Gemfile
Gemfile.lock
app/models/stage.rb
db/migrate/20190413103244_create_stages.rb
db/schema.rb
db/seeds.rb
spec/factories/stages.rb
spec/models/stage_spec.rb

[#89] Create the Stage model

---

app/models/rule.rb
db/migrate/20190413123632_create_rules.rb
db/schema.rb
db/seeds.rb
spec/factories/rules.rb
spec/models/rule_spec.rb

[#91] Create the Rule model

---

app/models/battle.rb
db/migrate/20190413133538_create_battles.rb
db/schema.rb
spec/factories/battles.rb
spec/models/battle_spec.rb

- Create the battles table
- Create the Battle model
- マッチごとのバトルの結果を保持できるようにする #88

[#88] Create the Battle model

---

app/models/tournament.rb
db/migrate/20190420060306_create_tournaments.rb
db/schema.rb
spec/factories/tournaments.rb
spec/models/tournament_spec.rb

[#94] Create the Tournament model

---

app/models/tournament.rb
db/migrate/20190421114835_add_name_on_tournament.rb
db/schema.rb
spec/factories/tournaments.rb
spec/models/tournament_spec.rb

[#96] Add the name column on tournaments table

---

app/models/match.rb
db/migrate/20190421124553_add_tournament_id_on_matches.rb
db/schema.rb
spec/factories/matches.rb
spec/models/match_spec.rb

- Tournament と Match に関連をもたせる #97

[#97] Add the tournamen_id on matches table

---

db/migrate/20190421153429_add_short_comment_on_teams.rb
db/schema.rb
spec/factories/teams.rb
spec/models/team_spec.rb

- Team に大会にむけての意気込みコメントカラムが欲しい #100

[#100] 意気込みをストアするカラムを追加

---

app/models/event.rb
db/migrate/20190421160654_add_code_and_numbering_on_events.rb
db/schema.rb
spec/factories/events.rb
spec/models/event_spec.rb

series_name x numbering で一意とする
- Event に numbering カラムが欲しい #101

[#101] event を表す native key を追加

---

db/migrate/20190427045306_add_switch_flag_and_order_in_team_on_participant.rb
db/schema.rb

Participants テーブルに swith doc 持ち込みの有無と team 内のorderカラムを足す

---

db/migrate/20190427051102_add_memo_on_reception.rb
db/schema.rb

同伴者何人いたかとか未成年が何人だとか同伴者の懇親会参加の有無だとかなんでもかけるフリーテキストカラム

Add memo on reception table

---

app/models/notice.rb
db/migrate/20190428153627_create_notices.rb
db/schema.rb
spec/factories/notices.rb
spec/models/notice_spec.rb

[#109] Create the Notice model
